### ISSUE TITLE
Proper release process

### ISSUE THREAD

**Issue by koenvervloesem** [rhasspy/rhasspy-services#2]
_Note: I'm creating this issue here because this applies to all Rhasspy services._

Rhasspy's services need a proper release process. We want to avoid publishing version X of a component as a package or Docker container while it still shows version X-1 in the source code (see https://community.rhasspy.org/t/fresh-install-sentences-ini-docker-version/49/5 for an example of the confusion that leads to).

To prevent errors, publishing a new release should be done in a consistent way, preferably as automatic as possible. I haven't found a good way to do this yet.

For [SnipsKit](https://github.com/koenvervloesem/snipskit) I followed this process (still manually):

- Check that all tests are passing
- [Check](https://github.com/koenvervloesem/snipskit/blob/master/scripts/check_examples.sh) that all example code in the documentation works.
- Change VERSION
- Change docs/source/CHANGELOG.rst
- `git add VERSION docs/source/CHANGELOG.rst`
- `git commit -m "Release: VERSION"`
- `git push`
- `git tag <version>`
- `git push origin --tags`
- Clean the local Git repository. Git stash possible polluters, or they could end up in the package, especially Python files or requirements files.
- Build the package
- Upload the package to PyPI
- Change VERSION to <version+1>-dev
- `git add VERSION`
- `git commit -m "Development version: VERSION"`
- `git push`

I didn't like the complexity of this process: it's still too manual, which leads to the possibility of errors. I searched for a way to automate this, but I didn't find something I liked.

Any comments on how we can do this for Rhasspy?

**Comment by koenvervloesem** [comment]
Maybe this can be automated partially with GitHub Actions (see also https://github.com/rhasspy/rhasspy-services/issues/5).

**Comment by synesthesiam** [comment]
Some of this should be handled by Travis CI, right? I figured we'd eventually have it set to auto-publish tagged builds. We should then at least be able to automatically run tests, do linting, verify that the git tag and VERSION match, and then build/upload the Docker images/Debian packages/PyPi packages.

**Comment by synesthesiam** [comment]
GitHub Actions look quite nice :)

**Comment by maxbachmann** [comment]
@koenvervloesem @synesthesiam 
I created https://github.com/maxbachmann/rhasspy-tag-action to help us with the release process.
It will automatically create a tag for a commit when the version in the `VERSION` file is incremented. Furthermore it allows the next step to check whether it was incremented aswell:
```
name: Bump version
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Bump version and push tag
      uses: rhasspy/rhasspy-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: bump_tag
    - name: update packages
      if: steps.bump_tag.outputs.new_tag
      run: <package-new-version-and-deploy>
```
this way it could trigger a deployment for the new version and we do not need to manually create the release tags anymore.

(I would move the repository into that rhasspy organisation,  but for whatever reasons you can only pass ownership either to a different user or a organisation in which you have the rights to create new repositories ...)
